version: '3.8'
services:
  database:
    image: mysql:8.4.0
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - acsoftware-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./node_modules:/node_modules
    depends_on:
      - database
    networks:
      - acsoftware-network
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0.1
#    ports:
#      - ${KEYCLOAK_PORT}:8080
#    environment:
#      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
#      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}  
#    command: start-dev --import-realm --log-level=DEBUG
#  minio:
#    image: quay.io/minio/minio:RELEASE.2024-04-06T05-26-02Z
#    ports:
#      - ${MINIO_API_PORT}:9000
#      - ${MINIO_UI_PORT}:9001
#    volumes:
#      - ./data/files:/data
#    environment: 
#      - MINIO_ROOT_USER=${MINIO_USER}
#      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
#    command: server /data --console-address ":9001"

networks:
  acsoftware-network:
    driver: bridge